version: "3.8"
services:
  frontend:
    build: ./ResumeBuilderAngular
    ports:
      - "4200:4200"
    depends_on:
      - backend
  backend:
    build: ./ResumeBuilderBackend
    ports:
      - "4292:4292"
  